### ISSUE TITLE
Newbie to SharePoint Online Add-Ins - Advice on Deploying an Add-In

### ISSUE THREAD

**Issue by jbartolome-sdcoe** [OfficeDev/SharePoint-Add-in-REST-OData-BasicDataOperations#3]
Hello,

I am fairly new to deploying add-in's to the SharePoint Online environment. I'm currently trying to install the BrandingAlternateCSSUrl sample code on our SharePoint Online environment, but I'm running into a sideloading of apps issue. I realize I'm working on a SPO website that is NOT a development website and I wanted to know what my options were to publish the add-in to the organization's add-in catalog. I'm using Visual Studio 2013 and the SharePoint Online environment - a publishing website. I'm happy to provide more details as needed, however, I would appreciate any start as to how-to release an add-in.

Thanks.

**Comment by Rick-Kirkham** [comment]
If you prefer to deploy the add-in using the SPO tenancy's add-in catalog instead of sideloading the add-in with F5 in Visual Studio, you can certainly do that. See [Deploying and installing SharePoint Add-ins: methods and options](https://msdn.microsoft.com/EN-US/library/office/fp179933.aspx) and [Set up an add-in catalog on Office 365](https://dev.office.com/docs/add-ins/publish/set-up-an-add-in-catalog-on-office-365).

**Comment by jbartolome-sdcoe** [comment]
Thank you, Rick. This was helpful!

In regards to setting up a project in Visual Studio for a new add-in, is there a template example that I may use to create a simple add-in to deploy to the store? I just need a foundation to work with and then I can go from there.

Thanks in advance!

**Comment by Rick-Kirkham** [comment]
When you create a SharePoint Add-in project in Visual Studio, a very simple, but complete, add-in is created, which you can deploy to an add-in catalog. You can use that as the foundation. You cannot, however, deploy to the Office Store. Add-ins that are marketed through the Office Store go through a quality validation process before they are allowed in the store. The simple add-in that is created by Visual Studio would not meet the standards.
